name: Terraform CI Validation

on:
  push:
    branches:
      - main
      - testing-ci

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -input=false -no-color
        working-directory: terraform